import java.util.Scanner;
import java.util.Random;

public class numguess{
    public static void main(String[] args){
        Boolean game = false;
        System.out.println("This is a game where you have to guess what a number generated by the computer is.\nYou have only 10 tries. Everytime you make a correct guess, you get 5 extra tries\nYou win when you make 3 correct guesses. If you run out of guesses, 'Game Over!!'\n");
        while(game==false){
            game = guess(game);
        }
        
    }
    public static Boolean guess(Boolean game){
        int guesses = 10;
        int correct_guess = 0;
        Scanner input  = new Scanner(System.in);
        while(game==false){
            int guess = random();
            System.out.println(guess);
            Boolean correct = false;
            while(correct==false){
                System.out.print("Enter your guess: ");
                int a = input.nextInt();
                if(a!=guess){
                    comment(a,guess);
                    correct=false;
                    guesses-=1;
                }else{
                    guesses+=5;
                    correct=true;
                    correct_guess+=1;
                    System.out.println("Correct!\n");
                }
            }
            if (guesses==0||correct_guess==3){
                game=true;
            }
        }
        input.close();
        return true;
    }
    public static int random(){
        Random num = new Random();
        int rand = num.nextInt(101);
        return rand;
    }
    public static void comment(int a,int b){
        int c = java.lang.Math.abs(a-b);
        if(c>10){
            if (c%10==0){
            }
            else{
                c = (c/10)*10;
            }
        }
        if (c<10){
            if(c<5){
                System.out.println("The guess is off by less than 5");
            }else{
                System.out.println("The guess is off by less than 10");
            }
        }
        else{
            System.out.printf("The guess is off by more than %d\n",c);
        }

    }
}